const FAMILY_USER = {
  GET_LIST_REQUEST: '[GET_FAMILY_USER_LIST] REQUEST',
  GET_LIST_SUCCESS: '[GET_FAMILY_USER_LIST] SUCCESS',
  GET_LIST_FAILURE: '[GET_FAMILY_USER_LIST] FAILURE'
};

export { FAMILY_USER };