const FAMILY_USER_DETAIL = {
  UPDATE_FAMILY_USER_REQUEST: '[UPDATE_FAMILY_USER] REQUEST',
  UPDATE_FAMILY_USER_SUCCESS: '[UPDATE_FAMILY_USER] SUCCESS',
  UPDATE_FAMILY_USER_FAILURE: '[UPDATE_FAMILY_USER] FAILURE',

  ACTIVATE_FAMILY_USER_REQUEST: '[ACTIVATE_FAMILY_USER] REQUEST',
  ACTIVATE_FAMILY_USER_SUCCESS: '[ACTIVATE_FAMILY_USER] SUCCESS',
  ACTIVATE_FAMILY_USER_FAILURE: '[ACTIVATE_FAMILY_USER] FAILURE',

  CLEAR_ACTIVATED_FAMILY_USER: '[ACTIVATED_FAMILY_USER] CLEAR'
};

export { FAMILY_USER_DETAIL };